name: Docker-Matrix
on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,ubuntu-22.04]
        image: [hello-world,alpine]
        exclude:
          - image: alpine
            os: windows-latest
        include:
          - image: nginx
            os: ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: badri.vaikunth@gmail.com
        password: ${{secrets.dockerpassword}}
    - name: Docker run
      run: docker run ${{matrix.image}}
